### ISSUE TITLE
BLACK Tag display issue, not working properly

### ISSUE THREAD

**Issue by sumotoy** [sumotoy/TFT_ILI9163C#1]
Can you provide a datasheet for this display?

**Comment by DDimitr** [comment]
Assuming that you are referring to a black PCB TFT sourced from Ebay, this is the documentation that was provided by the Ebay seller: https://www.dropbox.com/s/fwcoqy08thh5dzn/1.44Black_SPI.zip?dl=0

![_57](https://cloud.githubusercontent.com/assets/3502071/6387789/afb9bc56-bd99-11e4-9fab-c88fb6d34e68.JPG)
![_57 1](https://cloud.githubusercontent.com/assets/3502071/6387790/afbb7b9a-bd99-11e4-91b4-83b72c67f430.JPG)
![_57 2](https://cloud.githubusercontent.com/assets/3502071/6387791/afbe1a58-bd99-11e4-8e68-867290c3c221.JPG)
![_57 3](https://cloud.githubusercontent.com/assets/3502071/6387792/afc11f96-bd99-11e4-9e34-b30e4617af10.JPG)

**Comment by sp9mrn** [comment]
In my case "black" LCD has shifted display after first start. After tests -  BLACK does NOT need offset correction in library. 
I mean "offset" in "TFT_ILI9163C.h" shold be set to "0". Very good written library, clear and easy to make own corrections.

**Comment by sumotoy** [comment]
Oh, thanks! You confirm it works with what processor?
I have seen a Black tag that has the surrounding white display colored as Black that need offset.
At this point I presume there's more strain around!
Btw, I'm gonna update the whole library in  these days since it's an early alpha with the latest stuff (SPI transaction, etc) and try to figure out why with very fast MCU the screen refresh (done at high speed) produce a visible flash (I can see with the 3d example and Teensy3), also I'm plannig add a serious character support.

**Comment by MasudaNaika** [comment]
I forked your ILI9193C libray to use with my Arduino compatible boards. It uses AVR MSPIM.
https://github.com/MasudaNaika/TFT_ILI9163C
https://github.com/MasudaNaika/powerpack7

I tested 1.44 RED PCB (with wrong config) form ebay supplier and M014C9193SPI lcd module available in Japan.
http://www.aitendo.com/product/3857
M014C9193SPI module has correct configuration and the OFFSET should be zero to work.

I also noticed, even if with RED PCB, that const _GRAMSIZE = 128 \* 128 is enough to fill screen with your offset workaround.

mbed (Nucleo F411RE) version is here
http://developer.mbed.org/users/peu605/code/TFT_ILI9163C/

Thank you sumotoy.

**Comment by sp9mrn** [comment]
![h2](https://cloud.githubusercontent.com/assets/8061223/6390592/eb3cae5a-bdad-11e4-92e5-f3046dc15b79.jpg)  LCD connected to arduino mini 3,3v/8MHz. Also no problems with nano3 and uno. (with level shifters). 
1. I never tried to work with 5V - afraid to fry
2. Didn't try witn pro micro or leonardo (yet)

**Comment by castingflame** [comment]
I'll reload my setup and take a look at the offset sp9mrn mentions. Looking like a result!

**Comment by sumotoy** [comment]
Thanks Masuda for porting!
DDimitr, thanks for infos and pics, very useful. Looks like it's exact the same as the red pcb one.
sp9mrn, thanks for report! Btw ILI chip it's not 5V tolerant so driving at 5V I think it will fry it.
castingflame, wait for your report and thanks being here!

I just finish to setup a demo board (tomorrow I will post it) for update the library, if anyone have suggestions I will happy to include.
Till now here's my goals:
1) New SPI functions, bit more fast and SPI transaction compatible
2) Compatibility assured when other SPI devices uses same line (that's why I have to modify some SPI command)
3) Support for user character glyph set.

A note about tag (BLACK and RED). Adafruit use to sell this type of display time ago and they had a forniture of BLACK tag display that needed an offset correction, from some email exchange I had with an Adafruit reseller I just realize that this happened only for 100 displays and was probably an error of the display provider so no (teorically) we can stay at 0 offset.

**Comment by castingflame** [comment]
Its all a bit over my head but im learning fast and appreciate all your work for the community.

**Comment by MasudaNaika** [comment]
ILI9163 accepts continuous SPI data without toggling CS.

In ILI9163 library, most frequent called function are "setAddrWindow" and "fillRect".
If MCU's SPI has FIFO buffer, keeping CS low and sending continuous data  may improve performance.

e.g.
fillRect:  DC hi-> CS low -> send n of data -> CS high

A screen shot in link below may help to understand : First data has 4 bytes lengh with continuous 32 SCLKs. No pause in a transaction.
http://developer.mbed.org/media/uploads/peu605/ili9163_f411.jpg.pagespeed.ce.I2jsiCXX1g.jpg

In my case, 50MHz SPI clock worked properly on RED PCB.

Of course as you did, I think using Freescale's DSPI is the best solution.
Thanks again for your great work.

**Comment by sumotoy** [comment]
The new SPI code for Teensy do that, but I will try to use SPI DMA in the next days.
Thanks for info, I'll add the posting in the readme

**Comment by MasudaNaika** [comment]
Oops!, you have already implemented, excuse me...

**Comment by sumotoy** [comment]
Shinpai shinade...

**Comment by sumotoy** [comment]
ok, issue closed I think....

**Comment by sumotoy** [comment]
Masuda, I've corrected some stuff that was wrong, please check code and in particular fillScreen so if you ported the code you should reflect changes.
About GRAMSIZE, you can leave at 128x128 if you do not plan to use scroll (that I've just added). If so, scroll will use the off-screen ram (in short all mapped ram) and you prolly have garbage during scroll in one side of the screen!

**Comment by MasudaNaika** [comment]
Sumotoy, thank you inform me, I'lll check it.

**Comment by MasudaNaika** [comment]
I found you commented out,

```
void TFT_ILI9163C::defineScrollArea(uint16_t a,uint16_t c){
    //0,2
        uint16_t b;
        if ((a+c) > _TFTWIDTH) return;
        b = (_TFTWIDTH - (a+c));
        SPI.beginTransaction(SPISettings(SPICLOCK, MSBFIRST, SPI_MODE0));
        writecommand_cont(0x33);
        if (rotation == 0 || rotation > 1){
            writedata16_cont(a);
            writedata16_cont(b);
            writedata16_last(c);
        } else {
            writedata16_cont(a + __OFFSET);
            writedata16_cont(b + __OFFSET);
            writedata16_last(c + __OFFSET);
        }
        endProc();
        setAddr(0x00,0x00,_GRAMWIDTH-1,_GRAMHEIGH-1);
        setRotation(0);

}
```

According to the datasheet,  
"The 3rd & 4th parameter VSA[15...0] describes the height of the Vertical Scrolling Area (in No. of lines of the Frame Memory [not the display] from the Vertical Scrolling Start Address)"

```
    writedata16_cont(a + __OFFSET);
    writedata16_cont(b);    // <-
    writedata16_last(c);    // <-
```

Though I could not understand well what datasheet says about Vertical Scrolling Definition or Partial Area, I will try it tonight.

Sincerely

**Comment by sumotoy** [comment]
This is very important!

```
void TFT_ILI9163C::clearScreen(uint16_t color) {
    int px;
    #if defined(__MK20DX128__) || defined(__MK20DX256__)
        SPI.beginTransaction(SPISettings(SPICLOCK, MSBFIRST, SPI_MODE0));
        writecommand_cont(CMD_RAMWR);//this was missed!
        for (px = 0;px < _GRAMSIZE; px++){
            writedata16_cont(color);
        }
        _setAddrWindow(0x00,0x00,_GRAMWIDTH,_GRAMHEIGH);//go home
        writecommand_last(CMD_NOP);
        endProc();
    #else
        writecommand(CMD_RAMWR);
        for (px = 0;px < _GRAMSIZE; px++){
            writedata16(color);
        }
        setAddr(0x00,0x00,_GRAMWIDTH,_GRAMHEIGH);//go home
    #endif
}
```

Before I was use addressing, not correct!. Now I use ram write and pull addressing at the end since screen was cleared

About scrolling, I've not finished the defineScrollArea, just writed down, really thanks for help!
I've finished partialArea but trashed since looks useless, the area not active will result in a white screen, also display on/off looks useless, again white Screen. I suppose that ILI chip will pullup all unused area display drivers and pixels goes full on, a nonsense!
The scroll command works even without defining scroll area but with rotation 0 it's a vertical scroll and rotation 1 result a horizontal scroll, I'm not sure it will be easy to fix this, looks a pretty raw scroll feature.
Last thing, I hate ILI datasheet!

**Comment by MasudaNaika** [comment]
Sumotoy, I've just tried scrolling.

I leave GRAM_SIZE = 128 \* 128 and issue CMD_VSCLLDEF and CMD_VSSTADRS commands with OFFSET.
http://developer.mbed.org/users/peu605/code/TFT_ILI9163C/rev/1ebc27775d92

I've updoaded video to youtube.
http://youtu.be/wrQks3Npu1U

With Nucleo's SPI, I have to wait SPI become free every time toggling CS/DC.
If it's alright, translate to your code.

Best Regards

**Comment by MasudaNaika** [comment]
Umm, on my F411RE, without DMA is faster except fillScreen :-<

Nucleo F411RE DMA interrupt
Benchmark                Time (microseconds)
Screen fill              21032
Text                     11223
Lines                    34808
Horiz/Vert Lines         7809
Rectangles (outline)     7643
Rectangles (filled)      5896
Circles (filled)         19582
Circles (outline)        21612
Triangles (outline)      14020
Triangles (filled)       19307
Rounded rects (outline)  16900
Rounded rects (filled)   52690
Done!

Nucleo F411RE SOFT
Benchmark                Time (microseconds)
Screen fill              26290
Text                     6055
Lines                    28571
Horiz/Vert Lines         2609
Rectangles (outline)     2448
Rectangles (filled)      40189
Circles (filled)         14520
Circles (outline)        20814
Triangles (outline)      8331
Triangles (filled)       14443
Rounded rects (outline)  11330
Rounded rects (filled)   47627
Done!

**Comment by sumotoy** [comment]
Have to get back about clearScreen, the datasheet says one thing but in reality it's not!
Actual code works just fine (0.6b2) but I'm try to figure out why I need 2 commands and 6 data for simply write in ram! I'm sure there's a better and faster way to do that...
I'm sure that flashing on the botton of screen when I drive tft fast have something to do with this.

**Comment by sumotoy** [comment]
About SPI, in Teensy my tests showed that DMA it's overall faster but I have 50% slow down on circles (outline)

**Comment by MasudaNaika** [comment]
Good morning, sumotoy.

About clearScreen, I believe GRAMSIZE = 128 \* 128 is enough to fill visible area. Clearing invisible VRAM area consumes more time. 
If you use scroll, scroll area tfa should be tfa height + OFFSET, because a TFA value is the absolute address of frame memory.

I am speculating the actual configuration of RED PCB as below.
![ili9163con](https://cloud.githubusercontent.com/assets/1196296/6455151/c97c379c-c193-11e4-8b2c-fb83ca4174c9.png)

Any suggestions would be greatly appreciated.

**Comment by sumotoy** [comment]
It's bottom aligned, another fail of some chinese engineer. Infact I just got other 2 different display today (one red pcb and one black from 2 different vendors) correctly top aligned as it should be.
Thanks for the infos, it will be very informative for many users.

**Comment by MasudaNaika** [comment]
I draw the short straw...
But, I think, invisible vram area located on top of frame buffer may be  useful for some vertical scrolling game like XEVIOUS :-)

**Comment by sumotoy** [comment]
I've fixed finally clearScreen!

```
void TFT_ILI9163C::clearScreen(uint16_t color) {
    int px;
    #if defined(__MK20DX128__) || defined(__MK20DX256__)
        SPI.beginTransaction(SPISettings(SPICLOCK, MSBFIRST, SPI_MODE0));
        writecommand_cont(CMD_RAMWR);//this was missed!
        _setAddrWindow(0x00,0x00,_GRAMWIDTH,_GRAMHEIGH);
        for (px = 0;px < _GRAMSIZE; px++){
            writedata16_cont(color);
        }
        writecommand_last(CMD_NOP);
        endProc();
    #else
        writecommand(CMD_RAMWR);
        setAddr(0x00,0x00,_GRAMWIDTH,_GRAMHEIGH);//go home
        for (px = 0;px < _GRAMSIZE; px++){
            writedata16(color);
        }
    #endif
}
```

Without CMD_RAMWR before addressing in my display I got Always garbage when scrolling because it's the only command that uses the memory mapped out screen. The out-screen area will result as random point colors but with the new function will work.
Cannot find any mention of this in datasheet, would be great find another TFT aligned at top to see if this happen as well.
Btw it's not a big deal, just one call so the speed will not be so different.

**Comment by MasudaNaika** [comment]
Thank you hard working, sumotoy.

In my case, if limiting scroll area using defineScrollArea(0, 0) ( = CMD_VSCLLDEF, tfa =OFFSET, vsa =128, bfa=0), I think any garbage won't appear. 
I added "defineScrollArea(0, 0)" to TFT_ILI9163C::chipInit as default.

Youtube video shows vertical rolling scroll without any garbage. (but as you said, absolute scrolling axis is same in any rotation setting...)

**Comment by sumotoy** [comment]
Good catch! I think all issues are gone now, ready for the Gold Master!

**Comment by MasudaNaika** [comment]
Thank you sumotoy, this is a very nice library.
(If you don't mind, please try GRAM_SIZE = 128 \* 128 again. I hope you cannot  see any undesirable data during scroll.)

**Comment by sumotoy** [comment]
I tried but with bottom aligned display seems don't work, got garbage. Maybe the only workaround it's clear the ILI ram in the init GRAM_SIZE = 128 \* 160 then back to GRAM_SIZE = 128 \* 128.

**Comment by MasudaNaika** [comment]
Oh, it is disappointing. OK, Thanks for making time for me.

**Comment by sumotoy** [comment]
A pleasure Masuda, you help a lot!
