### ISSUE TITLE
Particle Photon

### ISSUE THREAD

**Issue by ineil** [sumotoy/TFT_ILI9163C#10]
Would you happen to know if this would work on Particle.io Photon devices?

**Comment by sumotoy** [comment]
I don't have any experience on Particle.io so I don't know wich processors they use, actually probably not but the way I wroted library uses preprocessor stantements based on MCU detected and all in the low level SPI calls (mostly in the .h file and the init in the .cpp file), you can expand to include other processor, it's not so difficult, take a look inside the code!
