### ISSUE TITLE
cp437 fix

### ISSUE THREAD

**Issue by sincetomorrow** [sumotoy/TFT_ILI9163C#11]
Hi!

Great library, it works great! 
Have you integrated the glcd font bug with the missing character?
(I am trying to put the ° character, but it show something else)
https://github.com/adafruit/Adafruit-GFX-Library/issues/22

Thank you very much,
Panos

**Comment by sumotoy** [comment]
Ah, ok. I'll fix this later.
In the next version of this library I will drop adafruit GFX, you will able to use your own font.

**Comment by sincetomorrow** [comment]
Hi again! Thanks for your quick replay. I have just noticed that I am using you newest library, in https://github.com/sumotoy/TFT_ILI9163C/tree/Pre-Release-1.0r, I have posted in this by mistake! In your new prelease, how do I access the degree sign?

Thanks a lot.

**Comment by sumotoy** [comment]
try xxx.setFont(GFXFONT_GLCD_ASCII);
The 1.0preview it's not the last code I'm working on, a brand new preview it's coming in some days and will use a different font scheme.
Le me know if still missing the char.
