### ISSUE TITLE
SDA to MOSI error - MISO Correct

### ISSUE THREAD

**Issue by marc-gist** [sumotoy/TFT_ILI9163C#15]
Your notes/readme says:

> SDA       -->     Mosi (3v3 level!) [Arduino pin 12]

when it should read

> SDA       --> MISO (3v3 level) (or Arduino pin 11)

Thanks for the great library!!

**Comment by sumotoy** [comment]
Ah, my fault, I will correct. Thanks

**Comment by sumotoy** [comment]
No, it should be <b>SDA --> MOSI (3v3 level) (or Arduino pin 11)</b>
I'm not using MISO at all.
Btw I cannot find this text, witch file?

**Comment by marc-gist** [comment]
Sorry... my bad... the pinout sheet i printed for the Arduino Pro Mini i'm using has an error on it. compared it to the ATMEGA pinout and you are correct... MOSI is pin 11.

text is in your readme file.
