### ISSUE TITLE
CC3200 with RA8875 on energia

### ISSUE THREAD

**Issue by leedennis519** [sumotoy/TFT_ILI9163C#19]
Hey, 

I tried ur library with Arduino UNO and it works perfectly, however, I'm trying to use the same library for CC3200 on energia and I wanted to ask what are some of the stuff that I would need to change for the RA8875 library to be compatible with CC3200 ?

Cheers,
Dennis

**Comment by sumotoy** [comment]
It's energia based if I'm not wrong?
I don't have CC3200, I have started time ago some kind of support for energia, I was suppose they provide a kind of SPI subset common to all devices but unfortunatly not so actually every device need his procedure, almost impossible without have phisically the device.
Actually it's not in my todo list, have to complete the 1.0 release, maybe in the future..

**Comment by leedennis519** [comment]
Cool, no worries I'll look into your stellaris framework, could probably
port it in there and do some minor hacks, thanks again.

**Comment by sumotoy** [comment]
stellaris was never tested! It was compiling long time ago but never tested actually...
