### ISSUE TITLE
Russian fonts

### ISSUE THREAD

**Issue by taranovegor** [sumotoy/TFT_ILI9163C#20]
How to add the Russian language to the library?
I have nice Russian font in Adafruit_GFX library, but he does not work with the Pre-Release library.

**Comment by sumotoy** [comment]
you have to wait the 1.0p4 release that allow to use external fonts (converted with LCD-Image-Converter).
The 1.0p4 will be released in some day, when all the small bugs are solved.

**Comment by taranovegor** [comment]
ok. thanks for your reply
