### ISSUE TITLE
externalFonts.ino needs different pin wiring then the other examples [workaround]

### ISSUE THREAD

**Issue by PiAir** [sumotoy/TFT_ILI9163C#25]
The externalFonts.ino (in TFT_ILI9163C-Pre-Release-1.0r4) does not use the rst pin and suggests to ty it to 3v3 (in the ESP8266 example). A lot of the other examples however require you to ty it to D2 / GPIO 4 for the ESP8266. 
Instead of changing the wiring I added 
  pinMode(__RST, OUTPUT);
  digitalWrite(__RST, HIGH);
to the setup. That fixed the problem also.

**Comment by sumotoy** [comment]
RST pin it's optional, some TFT have internal pullup, some not, depends of the chinese factory.
I have tested at list 7 different types and one of them refuse to work with 3v3 on RST, had to pullup with a resistor (6k8).
Generally the RST pin have some sense only during development but for normal operation better leave always UP, the initialization already perform a soft reset.
When I have some time I will write a wiki.
