### ISSUE TITLE
Antialiasing?

### ISSUE THREAD

**Issue by larsenglund** [sumotoy/TFT_ILI9163C#30]
Is it possible to use antialiased fonts? In your font guide (https://github.com/sumotoy/TFT_ILI9163C/wiki/Convert-fonts-for-1.0-release) you say that monochrome should be selected and it seems grayscale is needed for antialiasing..

**Comment by sumotoy** [comment]
Fonts file will be gigantic and rendering can be 10 time slower, this chip uses serial data. Better some kind of post antialiasing, I've seen some initial approach with pixel library but result are not so good.
I have planned only LRE compressed font for future.

**Comment by larsenglund** [comment]
Ok, thanks!
