### ISSUE TITLE
Double buffering?

### ISSUE THREAD

**Issue by larsenglund** [sumotoy/TFT_ILI9163C#31]
Are there any plans to support double buffering? ESP8266 is quite fast at 160MHz and har alot of RAM :)
Maybe using external RAM would be a viable option for other devices when you really don't want flickering..

**Comment by sumotoy** [comment]
Not plan. It uses too much ram, ESP use lot of ram for wifi operations.
To reduce flickering I'm actually tuning the init parameters.

**Comment by larsenglund** [comment]
Ok, thanks!
