### ISSUE TITLE
No offset for Red PCB V2.1 128x128

### ISSUE THREAD

**Issue by chashitsu** [sumotoy/TFT_ILI9163C#43]
For this display 128x128 there is no offset. This settings work well

```
    #define _TFTWIDTH       128//the REAL W resolution of the TFT
    #define _TFTHEIGHT      128//the REAL H resolution of the TFT
    #define _GRAMWIDTH      128
    #define _GRAMHEIGH      128//160
    #define _GRAMSIZE       _GRAMWIDTH * _GRAMHEIGH//*see note 1
    #define __COLORSPC      1// 1:GBR - 0:RGB
    #define __GAMMASET3     //uncomment for another gamma
    #define __OFFSET        0//*see note 2
```

Bought this: http://www.ebay.com/itm/171907483814?_trksid=p2057872.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT 

(Red PCB with Black pins)

Thank you very much for this project. I spent lot of time to get this cheap LCD working.

**Comment by sumotoy** [comment]
did you checked at ANY rotation first?
Also, this is know to use an ST7735, it may look work well on ILI9163C but several settings are ignored and other problems as well.
Also, this is referring the old version of ILI library, new one is here https://github.com/sumotoy/TFT_ILI9163C/tree/Pre-Release-1.0p7 and uses different settings.

For 2.1 you should check this https://github.com/sumotoy/TFT_ST7735/tree/1.0p1
