### ISSUE TITLE
Bug in display mode "3"

### ISSUE THREAD

**Issue by Edzelf** [sumotoy/TFT_ILI9163C#44]
In display mode "3" a part of the display can not be addressed.  The error is in lines 1096 and 1097.  They should read:
        _width  = _TFTHEIGHT;//-__OFFSET;
        _height = _TFTWIDTH;

**Comment by sumotoy** [comment]
This bug is referring to a library version is no more maintained.
Use the current one here 
https://github.com/sumotoy/TFT_ILI9163C/tree/Pre-Release-1.0p7
or the last development one
https://github.com/sumotoy/TFT_ILI9163C/tree/1.0p8
