### ISSUE TITLE
Help me with wemos and 1.44 LCD

### ISSUE THREAD

**Issue by peopledrivemecrazy** [sumotoy/TFT_ILI9163C#48]
Here are my connections 

| TFT LCD | WEMOS |
| --- | --- |
| VCC | 3.3V |
| GND | GND |
| CS | D8(15) |
| RST | 3.3V |
| A0 | 3.3V |
| SDA | D7(13) |
| SCL | D5(14) |
| LED | 3.3V |

But in the program there is a parameter "DC" which says to connect to pin 9 but my LCD module does not have a DC pin. All I see a white screen.
Thanks.

**Comment by sumotoy** [comment]
Did you read the library readme?

```
TFT side   -------------------- microprocessor  
- Vcc       -->     +3V3V(!!!!)
- Gnd       -->     Gnd
- CS        -->     CS pin (3v3 level!)
- RST       -->     connect to a MCU pin or tie to +3V3 or 10K to 3V3 (do NOT leave float!)
- A0        -->     DC or RS pin (3v3 level!)
- SDA       -->     Mosi (3v3 level!)
- SCK       -->     Sclk (3v3 level!)
- LED       -->     Some display need a resistor (see note below)
```

Set A0 to 3v3 it's not a good idea, display will never work. A0 is the DC pin.
