### ISSUE TITLE
Had a problem with the fonts when bigger than size 1 leave blank lines

### ISSUE THREAD

**Issue by victorpv** [sumotoy/TFT_ILI9163C#5]
I was adapting your library to the STM32F1 mcu, and noticed that the fonts were not rendering right when using a size bigger than 1.
On void TFT_ILI9163C::fillRect(
I have to change this line: for (x = w;x > 1;x--) {
For this line: for (x = w;x > 0;x--) {

Not sure if it is an issue only with the GFX library or the processor I am using, or is a general problem, so letting you know.

**Comment by sumotoy** [comment]
thanks, I will check and let you know

**Comment by sumotoy** [comment]
Look an issue of GFX library
