### ISSUE TITLE
Does this library work with 8MHz arduinos?

### ISSUE THREAD

**Issue by tymek22** [sumotoy/TFT_ILI9163C#6]
Does this library work with arduinos (or actually a bare atmega328p chip) which runs on the internal 8MHz oscillator? Or maybe 8MHz external crystal and not internal, but 8MHz and not 16MHz
I need that because this display is 3.3V and an atmega needs at least 4.5V to run at 16MHz so I want to switch to 8MHz so it can run on 3.3V. 
And will the spi output voltage be 3.3V if I supply the chip with 3.3V or will it still be 5V?

Thanks in advance!

**Comment by sp9mrn** [comment]
Yes. I use it with 3,3v 8MHz Mini

Maciek
sp9mrn

2015-04-25 15:59 GMT+02:00 tymek22 notifications@github.com:

**Comment by tymek22** [comment]
Ok thank you!
