### ISSUE TITLE
Drawing line doesn't fill fully line space

### ISSUE THREAD

**Issue by Puchaczov** [sumotoy/TFT_ILI9163C#8]
On arduino uno, there is a problem with drawing line with specific lenght

for example such code: 
  tft.drawFastHLine(0,0,128, RED);
doesn't fill in 100% line but there is 1 or 2 pixels with aren't filled by this line, same with VLine. 

It works when trying to supplement this pixels by drawPixel(...)

**Comment by sumotoy** [comment]
Did you try the new 1.0 preview?
https://github.com/sumotoy/TFT_ILI9163C/tree/Pre-Release-1.0r
It's also much faster but remember that in 1.0 I've dropped AdafruitGFX so you don't include (see 1.0 examples).
I have just tested with 1.0rc and doesn't have this problem.

Btw, I know where's the problem, I'll fix the old one

**Comment by Puchaczov** [comment]
In preview version drawFastHLine works correctly but vertical is still wrong.

tft.drawFastVLine(63,0,128,RED); I think the last pixel isn't filled correctly.

**Comment by sumotoy** [comment]
ok, thanks for digging this, I'll fix tonite.

**Comment by sumotoy** [comment]
tft.drawFastVLine(tft.width()/2,0,tft.height(),WHITE);

1 pixel loose, right?

**Comment by sumotoy** [comment]
It look fixed now. There was a problem similar with drawPixel as well.
I wait confirm...

**Comment by Puchaczov** [comment]
yea, looks fixed for me too, Great job and thanks :)
