### ISSUE TITLE
Rough estimate for Energia compatible version?

### ISSUE THREAD

**Issue by ortszentrum** [sumotoy/TFT_ILI9163C#9]
Hi,

This looks like an excellent project. I'd love to use your library to hook up my Adafruit TFT shield with my Redbearlab CC3200 (using the Energia IDE).

Do you have a rough sense when an Energia compatible version will be ready? Unfortunately, I don't have the skills to port it myself. 

Thanks a lot!

**Comment by sumotoy** [comment]
I don't have Redbearlab CC3200, have only the old Stellaris, btw I'm working on an importan update of this library so can you point me to a TFT library that works 'fast' with your CPU as study?

**Comment by ortszentrum** [comment]
Thanks for your comment. I haven't managed to get any TFT to work with the RBL CC3200 so far. I tried to use the 1.8" Adafruit TFT with the corresponding library from Adafruit and yours which I understand is based on it but I ran into difficulties with SPI and PROGMEM access.

**Comment by sumotoy** [comment]
Redbearlab CC3200 it's similar to Stellaris? (apart the wifi stuff obviously)
When I started this library not other exists, this is why I wroted it. I don't even know that an Adafruit library exists!
Time ago I wroted some code for Stellaris, there was some problems around SPI but I think they fixed now. The problem with Energia it's the slow development and most libraries are adapted from Arduino, btw the main development group it's small but experienced.
I had some problem asking infos, developers are busy with their work so forums are laying and questions are most of the time unaswered.
I have try to get some interest by adding energia support on some library but I never received any feedback, this is why my Energia good purposes are sleeping...

**Comment by tanahy** [comment]
I'm also interested in this port, I have a Tiva C series Launchpad (TM4C123G). I would gladly help to make it happen but I don't have the knowledge to develop it on my own, so some clues on where to get started or points to solve the compatibility issue would be really helpful.

**Comment by sumotoy** [comment]
I don't own a Tiva C, the Energia support it's painful, many processors, many differences.
It can help if you can point me to a working library that uses SPI.
